WiP lando environment
Currently getting connection refused because JDBC appears
to be trying to connect to localhost even though the correct
DATABASE_URL is detected in the environment:

www-data@d850df1729bc:/app$ clojure -A:dev -m rtc.app
Starting nREPL server at localhost:7000
Connecting to database at URL: jdbc:postgresql://dbhost/rtc?user=postgres
log4j:WARN No appenders could be found for logger (com.zaxxer.hikari.HikariConfig).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Apr 22, 2020 4:59:04 AM org.postgresql.core.v3.ConnectionFactoryImpl log
WARNING: ConnectException occurred while connecting to localhost:5432
java.net.ConnectException: Connection refused (Connection refused)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at org.postgresql.core.PGStream.<init>(PGStream.java:69)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:156)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
        at org.postgresql.Driver.makeConnection(Driver.java:452)
        at org.postgresql.Driver.connect(Driver.java:254)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
        at clojure.java.jdbc$get_driver_connection.invokeStatic(jdbc.clj:271)
        at clojure.java.jdbc$get_driver_connection.invoke(jdbc.clj:250)
        at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:411)
        at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
        at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:343)
        at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
        at migratus.database$connect_STAR_$fn__9239.invoke(database.clj:122)
        at migratus.database$connect_STAR_.invokeStatic(database.clj:121)
        at migratus.database$connect_STAR_.invoke(database.clj:114)
        at migratus.database.Database.init(database.clj:248)
        at migratus.core$init.invokeStatic(core.clj:142)
        at migratus.core$init.doInvoke(core.clj:139)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at rtc.db$eval9488$fn__9489.invoke(db.clj:92)
        at mount.core$record_BANG_.invokeStatic(core.cljc:74)
        at mount.core$record_BANG_.invoke(core.cljc:73)
        at mount.core$up$fn__258.invoke(core.cljc:81)
        at mount.core$up.invokeStatic(core.cljc:80)
        at mount.core$up.invoke(core.cljc:78)
        at mount.core$bring.invokeStatic(core.cljc:247)
        at mount.core$bring.invoke(core.cljc:239)
        at mount.core$start.invokeStatic(core.cljc:289)
        at mount.core$start.doInvoke(core.cljc:281)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at rtc.app$_main.invokeStatic(app.clj:50)
        at rtc.app$_main.doInvoke(app.clj:49)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
/tmp/clojure-598432307149804951.edn